# https://services.shopify.io/services/go-rspamd
org_line: Production Engineering
owners:
- Shopify/notification-platform-eng
audience: internal
classification: library
slack_channels:
    - courier-operations
